name: example-command
on:
  workflow_dispatch:
    types: [example-command]
    inputs:
      comment-id:
        description: 'comment-id to use'
        required: true
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ github.event.inputs.comment-id }}
          reactions: hooray
