name: Manual Rollback Test

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target Environment'
        required: true
        default: 'dev'
      sha:
        description: 'Target commit hash'
        required: true

jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          sha: ${{ github.event.inputs.sha }}
      - name: Deploy
        run: |
          echo "Deploying build ${{ github.event.inputs.sha }} to ${{ github.event.inputs.environment }}"
