name: Manual Workflow Test

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target Environment'
        required: true
        default: 'dev'
      commit-sha:
        description: 'Target commit hash'
        required: true
        default: ${{ github.sha }}

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Deploy
        run: |
          echo "Deploying build ${{ github.event.inputs.commit-sha }} to ${{ github.event.inputs.environment }}"
