name: Manual Rollback

on:
  workflow_dispatch:
    types: [rollback-command]
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'dev'
      sha:
        description: 'Target commit hash'
        required: true

jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.sha }}
      - name: Deploy
        run: |
          echo "Deploying build ${{ github.event.inputs.sha }} to ${{ github.event.inputs.environment }}"
