name: Rollback Command Dispatch
on:
  issue_comment:
    types: [created]
jobs:
  rollbackCommandDispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Rollback Command Dispatch
        uses: peter-evans/slash-command-dispatch@v4
        with:
          token: {{ $secrets.PAT }}
          commands: rollback
