name: Manual Rollback

on:
  repository_dispatch:
    types: [rollback-command]
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'dev'
      sha:
        description: 'Target commit hash'
        required: true

jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.slash_command.args.named.sha }}
      - name: Deploy
        run: |
          echo "Deploying build ${{ github.event.client_payload.slash_command.args.named.sha }} to ${{ github.event.client_payload.slash_command.args.named.environment }}"
