name: rollback-command
on:
  workflow_dispatch:
    types: [rollback-command]
    inputs:
      commit-sha:
        description: 'target rollback commit'
        required: true
        default: ${{ github.sha }}

jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.commit-sha }}
      - name: Rollback
        run: |
          echo "Will deploy ${{ github.event.inputs.commit-sha }}"
