name: Slash Command Dispatch
on:
  issue_comment:
    types: [created]
jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
      - name: Slash Command Dispatch Rollback
        uses: peter-evans/slash-command-dispatch@v4
        with:
          token: ${{ secrets.PAT }}
          commands: |
            rollback
